### ISSUE TITLE
Consider extending BeanShell's BshScriptEngine

### ISSUE THREAD

**Issue by ctrueden** [scijava/scripting-beanshell#2]
We briefly switched to BeanShell's built-in JSR-223 `ScriptEngineFactory`—see f17c2fd530375158c2f22a58add367c49215e6c7. However, that behaves in a way inconsistent with Java—e.g.:

``` java
a = null;
print(a == null ? "NULL" : "HUH?");
```

prints `HUH?` instead of `NULL` as expected.

So for now we reverted back to our own custom implementation: a64b736c95d6815061459bdfcb04f52e79db65d4.

It would be ideal to use the `BshScriptEngine` for DRYness, but extend it as succinctly as possible to avoid the incompatible behavior above.

See also [this forum thread](http://forum.imagej.net/t/can-bsh-jar-be-updated-to-latest-version/1115).

**Comment by subes** [comment]
I have packaged the release of [beanshell 2.1.0](https://github.com/beanshell/beanshell/releases/tag/2.1.0) here: https://invesdwin.de/nexus/#browse/search=keyword%3D%22org%2Fapache-extras%2Fbeanshell%2Fbsh%2F2.1.0%22:e3825b2faa78e6fff7ba00d5d8e717f5

I had to fix the scriptengine service file because it used the wrong package name in the official release.

This package works with JSR233 without the confusion about null vs void.

Testcases are available here: https://github.com/invesdwin/invesdwin-context/tree/master/invesdwin-context-parent/invesdwin-context-beanshell

**Comment by ctrueden** [comment]
@subes Thanks very much for the heads up! I have added a proxy for invesdwin-oss repository to maven.scijava.org, so that the SciJava community can access this work seamlessly. And I pushed commits updating this repository to BeanShell 2.1.0.
